version: '3.3'

services:  
  redis:
    image: redis
    container_name: cache
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    ports:
      - '6379:6379'
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\" &&
      exec redis-cli -a \"${REDIS_PASSWORD}\" config set client-output-buffer-limit \"pubsub 64mb 32mb 120\""]

  binance:
    build: Binance/ 
    image: binance
    container_name: binance
    depends_on:
      - redis
    networks:
      - redis-net
    env_file:
      - ./.env
    environment:
      - REDIS_URL=cache

  kraken:
    build: Kraken/ 
    image: kraken
    container_name: kraken
    depends_on:
      - redis
    networks:
      - redis-net
    env_file:
      - ./.env
    environment:
      - REDIS_URL=cache

  aggregator:
    build: Aggregator/ 
    image: aggregator
    container_name: aggregator
    depends_on:
      - redis
      - binance
      - kraken
    networks:
      - redis-net
    env_file:
      - ./.env
    environment:
      - REDIS_URL=cache

  backend:
    build: Back-end/
    image: backend
    container_name: backend
    networks:
      - redis-net
      #- nginx-net
    expose:
      - 5000
    ports:
      - '5000:5000'
    volumes:
      - ./Back-end:/Back-end
    depends_on:
      - redis
      - binance
      - kraken
    env_file:
      - ./.env
    environment:
      - REDIS_URL=cache

  nginx:
    restart: always
    image: nginx:latest
    depends_on:
      - backend
    #networks:
      #- nginx-net
    expose:
      - 80
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - HOST=backend

networks:
  redis-net:
  #nginx-net:

volumes:
  redis-data:
